---
title: "Facet"
output: html_document
date: "2024-03-17"
---

# https://r-charts.com/ggplot2/axis/

```{r}
library(ggplot2)
library(patchwork)
```

# Axis titles

```{r}
g1=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ labs(x = "The type of drive train", y = "Engine displacement, in litres") 
g2=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ xlab("The type of drive train")
g1+g2
```

# Axis labels

```{r}
g1=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ 
  labs(x = "The type of drive train", y = "Engine displacement, in litres") +
  scale_x_discrete(label = c("4wd","front-wheel drive","rear wheel drive"))

g2=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ 
  labs(x = "The type of drive train", y = "Engine displacement, in litres") +
  scale_x_discrete(label = c("4wd","front-wheel drive","rear wheel drive"))+
  theme(axis.text = element_text(color = "slateblue",
                                size = 10))

g1+g2
```
## Font type
```{r}
g1=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ 
  labs(x = "The type of drive train", y = "Engine displacement, in litres") +
  scale_x_discrete(label = c("4wd","front-wheel drive","rear wheel drive"))+
  theme(text = element_text(family = "Times New Roman"))

g2=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ 
  labs(x = "The type of drive train", y = "Engine displacement, in litres") +
  scale_x_discrete(label = c("4wd","front-wheel drive","rear wheel drive"))+
  theme(plot.title    = element_text(family = "mono"),
        plot.subtitle = element_text(family = "sans"),
        axis.title.x  = element_text(family = "Comic Sans MS"),
        axis.title.y  = element_text(family = "AppleGothic"),
        axis.text.x   = element_text(family = "Optima"),
        axis.text.y   = element_text(family = "Luminari"))

g1+g2
##On a Mac, you can go to the “Font Book” application and have a look at the list of fonts there. 
```

# Axis ticks
```{r}
ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ labs(x = "The type of drive train", y = "Engine displacement, in litres") + scale_y_continuous(breaks = seq(0, 7, by = 0.5))
```

# Axis limits: zoom in or subset
```{r}
g1=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ labs(x = "The type of drive train", y = "Engine displacement, in litres")+coord_cartesian(ylim = c(1.5, 5))
g2=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ xlab("The type of drive train")+ylim(c(1.5, 5))
g3=ggplot(mpg, aes(x = drv, y = displ)) +
      geom_boxplot()+ xlab("The type of drive train")+expand_limits(x = 0, y = 0)
g1+g2+g3
```
# Axis scales
```{r}
g1=ggplot(midwest, aes(x = area,y = poptotal)) +
  geom_point() +
  geom_smooth()
g2=ggplot(midwest, aes(x = area,y = poptotal)) +
  geom_point() +
  geom_smooth()+ scale_y_sqrt()
g3=ggplot(midwest, aes(x = area,y = poptotal)) +
  geom_point() +
  geom_smooth()+ scale_y_log10()
g1+g2+g3
```


a