---
title: "Save_images"
output:
  html_document: default
  pdf_document: default
date: "2024-05-12"
---
```{r}
library(ggplot2)
library(ggpubr)
library(patchwork)
```

```{r}
set.seed(3)
x1 <- rnorm(100, mean=1)
x2 <- rnorm(100, mean = 3)
x <- c(x1, x2)
group <- c(rep("G1", 100), rep("G2", 100))

df <- data.frame(x, group_G1_G2 = group)
df
```

## Save the plot using ggsave

```{r fig.width=5,fig.height=2}
g1=ggplot(df, aes(x = x, fill = group_G1_G2, colour= group_G1_G2)) + 
  geom_histogram(alpha = 0.5)

g2=ggplot(df, aes(x = x, fill = group_G1_G2, colour= group_G1_G2)) + 
  geom_histogram(alpha = 0.5, position = "identity")

g=g1+g2
g
```

```{r}
ggsave("histogram.png",plot = g, width = 12, height = 4)

ggsave("histogram.pdf",plot = g, width = 12, height = 4)
```


### ggplot saves the last plot that you displayed by default

```{r fig.width=5,fig.height=4}
g_paired=ggpaired(ChickWeight[ChickWeight$Diet==1,], x = "Time", y = "weight",id = "Chick",
 color = "Time", line.color = "gray", line.size = 0.4,xlab = "Time", ylab = "weight")
g_paired+g_paired
```
# Save figures generated by basic R
```{r}
for (i in 1:5){
  featurename=colnames(mtcars)[i]
  figname=paste(c(featurename,".png"),collapse = "")
  png(file=figname, width = 1200, height = 900,res = 200)
  hist(mtcars[,i],xlab = featurename)
  dev.off()
}
```

